--
DROP TABLE VIDEO IF EXISTS;
DROP TABLE RATING IF EXISTS;

--
DROP SEQUENCE SEQ_VIDEO IF EXISTS;
DROP SEQUENCE SEQ_RATING IF EXISTS;

--
CREATE SEQUENCE SEQ_VIDEO START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RATING START WITH 20 INCREMENT BY 1;


CREATE TABLE VIDEO (
ID BIGINT PRIMARY KEY,
MOVIE_TITLE VARCHAR(255) NOT NULL,
IS_CHECKED_OUT BOOLEAN DEFAULT FALSE NOT NULL,
RATING NUMERIC (19, 2),
);

CREATE TABLE RATING (
ID BIGINT PRIMARY KEY,
VIDEO_ID BIGINT NOT NULL,
VIDEO_RATING BIGINT NOT NULL,
);



